name: ReitzMMO
version: 1.0
author: Paully104
main: com.paully104.reitzmmo.Main
commands:
        ReitzMMO:
                     description: Main ReitzRPGMMO command listings
                     usage: /ReitzRPGMMO
        RRM:
                     description: Main ReitzRPGMMO command listings
                     usage: /RRM
