name: ReitzMMO
version: 1.0
author: Paully104
main: com.paully104.reitzmmo.Main
commands:
        reitz:
                     description: Main ReitzRPGMMO command listings
                     usage: /reitz
        rrm:
                     description: Main ReitzRPGMMO command listings
                     usage: /rrm
        rparty:
                    description: Party system for ReitzRPGMMO
                    usage: /rparty

